//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramiranjeASP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class aboutme
    {
        public int abId { get; set; }
        public string aboutTitle { get; set; }
        public string aboutText { get; set; }
        public string aboutFB { get; set; }
        public string aboutInsta { get; set; }
        public string aboutG { get; set; }
        public string aboutOut { get; set; }
    }
}
