//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramiranjeASP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class home
    {
        public int homeId { get; set; }
        public string block_title { get; set; }
        public string block_text { get; set; }
    }
}
