//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramiranjeASP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class seventh
    {
        public int seId { get; set; }
        public string seTitle { get; set; }
        public string seText { get; set; }
    }
}
