//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramiranjeASP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.userFunctions = new HashSet<userFunction>();
        }
    
        public int userId { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string mail { get; set; }
    
        public virtual ICollection<userFunction> userFunctions { get; set; }
    }
}
