//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramiranjeASP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class userFunction
    {
        public int ufId { get; set; }
        public int id_user { get; set; }
        public int id_function { get; set; }
    
        public virtual function function { get; set; }
        public virtual user user { get; set; }
    }
}
